services:
  db:
    image: timescale/timescaledb:2.12.1-pg15
    container_name: timescale_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: helpdesk
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - timescale_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 40
    networks:
      - app-network

  # Docker in Docker (for Maven builds or other Docker-related tasks)
  dind:
    image: docker:20.10.24-dind
    container_name: dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    volumes:
      - dind-data:/var/lib/docker
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "docker info > /dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  maven:
    image: maven:3.9.5-eclipse-temurin-17
    container_name: maven
    volumes:
      - .:/app
    working_dir: /app
    environment:
      DOCKER_HOST: tcp://dind:2375
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
      dind:
        condition: service_healthy
    command: mvn clean package
    deploy:
      restart_policy:
        condition: none

  eureka-server:
    image: eclipse-temurin:17-jdk
    container_name: eureka_server
    ports:
      - "8761:8761"
    volumes:
      - ./eureka-server:/app
    working_dir: /app
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
      maven:
        condition: service_completed_successfully
    entrypoint: ["java", "-jar", "/app/target/eureka-server-0.0.1-SNAPSHOT.jar"]
    environment:
      SPRING_PROFILES_ACTIVE: docker
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8761/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    image: eclipse-temurin:17-jdk
    container_name: user_service
    ports:
      - "8081:8081"
    volumes:
      - ./user-service:/app
    working_dir: /app
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    entrypoint: ["java", "-jar", "/app/target/user-service-0.0.1-SNAPSHOT.jar"]
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/helpdesk
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_APPLICATION_NAME: user-service

  ticket-service:
    image: eclipse-temurin:17-jdk
    container_name: ticket_service
    ports:
      - "8082:8082"
    volumes:
      - ./ticket-service:/app
    working_dir: /app
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    entrypoint: ["java", "-jar", "/app/target/ticket-service-0.0.1-SNAPSHOT.jar"]
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/helpdesk
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_APPLICATION_NAME: ticket-service

volumes:
  timescale_data:
  dind-data:

networks:
  app-network:
