name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  ci:
    name: Build and Keep Containers Active
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Make
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Run Make Rebuild
        run: make rebuild

      - name: Verify App Health
        run: |
          echo "Waiting for TICKET-SERVICE to be ready..."
          for i in {1..30}; do
            response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8082/api/tickets/health)
            echo "TICKET-SERVICE health check returned status: $response"
            if [ "$response" -eq 200 ]; then
              break
            fi
            echo "TICKET-SERVICE not ready, retrying in 5 seconds..."
            sleep 5
          done
          if [ "$response" -ne 200 ]; then
            echo "TICKET-SERVICE failed to start within the expected time."
            exit 1
          fi
          
          echo "Waiting for USER-SERVICE to be ready..."
          for i in {1..30}; do
            response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8081/api/users/health)
            echo "USER-SERVICE health check returned status: $response"
            if [ "$response" -eq 200 ]; then
              break
            fi
            echo "USER-SERVICE not ready, retrying in 5 seconds..."
            sleep 5
          done
          if [ "$response" -ne 200 ]; then
            echo "USER-SERVICE failed to start within the expected time."
            exit 1
          fi

      - name: Teardown
        if: always()
        run: make down
