name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  ci:
    name: Build and Keep Containers Active
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Make
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Run Make Rebuild
        run: make rebuild

      - name: Verify App Health
        run: |
          echo "Waiting for the app to be ready..."
          for i in {1..30}; do
            curl -f http://localhost:8080/api/tickets/health && break || echo "App not ready, retrying in 5 seconds..."
            sleep 5
          done
          if ! curl -f http://localhost:8080/api/tickets/health; then
            echo "App failed to start within the expected time."
            exit 1
          fi

      - name: Cleanup on Error
        if: failure()
        run: make down
